Adds an S3 client and upload & download functions
hyqe/brigand pull request #32
Opened 2023-05-12 23:58 UTC by LukeOchoa

2023-05-13 01:48 UTC, jakobii requested changes

2023-05-13 01:49 UTC, LukeOchoa commented on internal/storage/digital_ocean_s3.go
> +package storage
This is a comment

2023-05-13 01:49 UTC, LukeOchoa commented on go.mod
Do you see this?

2023-05-13 02:06 UTC, LukeOchoa commented
Relocated all envs into config file.

2023-05-18 18:23 UTC, jakobii approved these changes

2023-05-18 18:24 UTC, merged